name: Automated API Tests using Newman

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install Node.js (needed for Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Verifique a versão necessária

      # Step 3: Install Newman and HTML Extra reporter
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Install Repost    
      - name: Install Report html extra
        run: sudo npm install -g newman-reporter-htmlextra          

      # Step 5: Run Newman with the collection and environment files
      - name: Run API tests with Newman and HTML Extra
        run: newman run ./tests/Hunter_collection.postman_test_run.json -e ./tests/desenvolvimento.postman_environment.json \
          --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/report.html

      # Step 6: Upload the HTML report as an artifact
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: api-test-html-report
          path: ./results/report.html
