name: Automated API Tests using Newman

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install Node.js (needed for Newman)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Verifique a versão necessária

      # Step 3: Install Newman and HTML Extra reporter
      - name: Install Newman and HTML Extra
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra@1.23.1

      # Step 4: Run Newman with the collection and environment files
      - name: Run API tests with Newman and HTML Extra
        run: |
          newman run ./tests/Hunter_collection.postman_test_run.json -e ./tests/desenvolvimento.postman_environment.json \
          --reporters cli, -r htmlextra --reporter-htmlextra-export ./tests/report/report.html

      # Step 5: Upload the HTML report as an artifact
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: api-test-html-report
          path: ./tests/report.html
